### ISSUE TITLE
login gif

### ISSUE THREAD

**Issue by keyboardsejong** [osamhack2021/app_web_dronai_62bn#1]
![Animation2](https://user-images.githubusercontent.com/89467983/137246368-1da3a483-9081-4144-8381-ba4dc3d8b489.gif)

**Comment by keyboardsejong** [comment]
![image](https://user-images.githubusercontent.com/89467983/137246513-13532625-14f4-4d15-9665-fa657dd5cfd4.png)

**Comment by LINEARJUN** [comment]
깔끔한 이미지로 대체 (closed)
